[package]
name = "datadog-export"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
crabber = { path = "../../crates/crabber", features = ["datadog"] }
crabber-obs = { path = "../../crates/crabber-obs" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
