[package]
name = "crabber-guest"
version.workspace = true
edition.workspace = true
license.workspace = true
include = ["Cargo.toml", "README.md", "src/**", "wit/**"]

[dependencies]
wit-bindgen = "=0.62.0"
serde_json = "1"
crabber-guest-macros = { path = "../crabber-guest-macros" }

[lints]
workspace = true
